eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka:
      value: true
    fetch-registry:
      value: true
    instance:
      hostname: localhost